import {Colors} from '@src/styles/colors';
import {ms, s} from '@src/styles/scalingUtils';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  listDetailContainer: {
    paddingVertical: s(10),
    borderBottomColor: Colors.borderColor,
    borderBottomWidth: s(1),
    paddingHorizontal: s(10),
  },
  listDetailTen: {
    color: Colors.primaryColor,
  },
  listDetailView: {
    flex: 1,
    flexDirection: 'row',
    marginTop: s(5),
    justifyContent: 'space-between',
  },
  listDetailQuantity: {
    fontFamily: 'Roboto-Regular',
    fontSize: s(13),
  },
  lisDetailAmount: {
    fontFamily: 'Roboto-Bold',
    fontSize: s(13),
    color: Colors.dark,
    textAlign: 'right',
  },
  viewGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewText: {
    width: '30%',
    fontFamily: 'Roboto-Regular',
    fontSize: s(13),
    color: Colors.textColor,
    paddingVertical: s(5),
  },
  viewInputText: {
    fontFamily: 'Roboto-Medium',
    fontSize: s(14),
    color: Colors.textColor,
    borderBottomColor: Colors.borderColor,
    borderBottomWidth: s(1),
    flex: 1,
    paddingVertical: s(11),
  },
  groupView: {
    flex: 1,
    flexDirection: 'column',
    paddingHorizontal: s(10),
  },
  groupViewName: {
    fontFamily: 'Roboto-Bold',
    fontSize: s(15),
    color: Colors.primaryColor,
    marginVertical: s(10),
  },
  groupViewContent: {
    fontFamily: 'Roboto-Medium',
    fontSize: s(13),
    color: Colors.manatee,
    marginBottom: s(10),
  },
  groupViewHeader: {
    flex: 1,
    padding: s(10),
    backgroundColor: Colors.primaryColor05,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  groupViewHeaderText: {
    fontFamily: 'Roboto-Bold',
    fontSize: s(14),
    color: Colors.primaryColor,
  },
  groupViewDetail: {
    flex: 1,
    paddingHorizontal: s(10),
    paddingBottom: s(10),
  },
  groupViewAmount: {
    flex: 1,
    padding: s(10),
    backgroundColor: Colors.primaryColor05,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  groupViewSub: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  groupViewTextLeft: {
    fontFamily: 'Roboto-Regular',
    fontSize: s(13),
    color: Colors.textColor,
  },
  groupViewTextRight: {
    fontFamily: 'Roboto-Bold',
    fontSize: s(14),
    color: Colors.red,
  },
  checkboxContainer: {
    backgroundColor: Colors.white,
    borderWidth: 0,
    padding: 0,
    margin: 0,
    justifyContent: 'center',
    marginVertical: ms(20),
  },
  itemRow: {
    flexDirection: 'row',
    paddingHorizontal: ms(2),
  },
  itemRowColumnFirst: {
    flexDirection: 'column',
  },
  itemRowColumn: {
    paddingLeft: ms(9),
    paddingVertical: ms(4),
    justifyContent: 'center',
  },
  itemRowHeader: {
    fontFamily: 'Roboto',
    fontSize: s(13),
    paddingVertical: s(5),
    color: Colors.black,
    fontWeight: 'bold',
  },
  itemRowDetail: {
    fontFamily: 'Roboto-Regular',
    fontSize: s(11),
    color: Colors.black,
  },
  emptyView: {
    flex: 1,
    alignItems: 'center',
    marginTop: s(40),
  },
  groupButton: {
    marginBottom: ms(30),
    height: ms(31),
    borderWidth: ms(1),
    backgroundColor: Colors.primaryColor,
    borderColor: Colors.primaryColor,
    borderRadius: ms(5),
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowOffset: {
      width: ms(2),
      height: ms(4),
    },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginHorizontal: ms(8),
    paddingVertical: ms(4),
    paddingHorizontal: ms(25),
  },
  btnTouch: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: {
    fontFamily: 'Roboto-Bold',
    color: 'white',
  },
  txtBold: {
    fontSize: ms(14),
    lineHeight: ms(16),
    color: Colors.black,
    fontWeight: 'bold',
  },
  txt: {
    fontSize: ms(14),
    lineHeight: ms(16),
    color: Colors.black,
  },
  emptyText: {
    fontSize: 15,
    fontFamily: 'Roboto-Medium',
    color: Colors.primaryColor,
  },
  itemContainer: {
    flexDirection: 'column',
  },
  btnScan: {
    width: ms(220),
    height: ms(33),
    backgroundColor: Colors.white,
    borderColor: Colors.backgroundImg,
    borderWidth: ms(1),
    borderRadius: ms(5),
    justifyContent: 'center',
    paddingLeft: ms(8),
    fontSize: ms(11),
    lineHeight: ms(16)
  },
  txtInput: {
    color: '#A6A6A6',
    fontSize: ms(11),
    width: ms(220),
    height: ms(33),
    backgroundColor: Colors.white,
    borderColor: Colors.backgroundImg,
    borderWidth: ms(1),
    borderRadius: ms(5),
    marginBottom: ms(12),
    paddingLeft: ms(8),
  },
  btnSL: {
    borderWidth: ms(1),
    backgroundColor: Colors.primaryColor,
    borderColor: Colors.primaryColor,
    borderRadius: ms(5),
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowOffset: {
      width: ms(2),
      height: ms(4),
    },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: ms(8),
    paddingVertical: ms(4),
    paddingHorizontal: ms(16),
  },
});

export default styles;
